global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monitor'
    static_configs:
      - targets:
        - 'agg-eu-west.railway.internal:2112'
        - 'alert-reflection.railway.internal:2112'
        - 'aggregator-latency-benchmark.railway.internal:2112'
    metrics_path: /metrics

