global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'latency_monitor'
    static_configs:
      - targets: ['monitor:2112']
        labels:
          app: 'aggregator_latency_monitor'
          environment: 'production'
