global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'latency_monitor'
    static_configs:
      - targets: ['aggregator-latency-benchmark-production.up.railway.app:443']
    scheme: https
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: false

